### ISSUE TITLE
I/O redirect used in submit command causes failure/exception

### ISSUE THREAD

**Issue by sgenie68** [grisu/grisu#60]
submit "command <input" causes exception:

Fatal Error] :19:66: The content of elements must consist of well-formed character data or markup.
java.lang.RuntimeException: org.xml.sax.SAXParseException: The content of elements must consist of well-formed character data or markup.
    at grisu.utils.SeveralXMLHelpers.fromString(SeveralXMLHelpers.java:257)
    at grisu.utils.SimpleJsdlBuilder.buildJsdl(SimpleJsdlBuilder.java:175)
    at grisu.model.job.JobSubmissionObjectImpl.getJobDescriptionDocument(JobSubmissionObjectImpl.java:412)
    at grisu.model.job.JobSubmissionObjectImpl.getJobDescriptionDocumentAsString(JobSubmissionObjectImpl.java:432)
    at grisu.frontend.model.job.JobObject.createJob(JobObject.java:460)
    at grisu.gricli.command.SubmitCommand.createJob(SubmitCommand.java:39)
    at grisu.gricli.command.SubmitCommand.execute(SubmitCommand.java:50)
    at grisu.gricli.Gricli.runCommand(Gricli.java:203)
    at grisu.gricli.Gricli.executionLoop(Gricli.java:86)
    at grisu.gricli.Gricli.main(Gricli.java:178)
Caused by: org.xml.sax.SAXParseException: The content of elements must consist of well-formed character data or markup.
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:239)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:283)
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:124)
    at grisu.utils.SeveralXMLHelpers.fromString(SeveralXMLHelpers.java:251)
    ... 9 more
command failed. Either connection to server failed, or this is gricli bug. Please send /home/gsou008/.grisu.beta/gricli.debug to eresearch-admin@auckland.ac.nz together with description of what triggered the problem
java.lang.RuntimeException: Couldn't create jsdl document
    at grisu.utils.SimpleJsdlBuilder.buildJsdl(SimpleJsdlBuilder.java:179)
    at grisu.model.job.JobSubmissionObjectImpl.getJobDescriptionDocument(JobSubmissionObjectImpl.java:412)
    at grisu.model.job.JobSubmissionObjectImpl.getJobDescriptionDocumentAsString(JobSubmissionObjectImpl.java:432)
    at grisu.frontend.model.job.JobObject.createJob(JobObject.java:460)
    at grisu.gricli.command.SubmitCommand.createJob(SubmitCommand.java:39)
    at grisu.gricli.command.SubmitCommand.execute(SubmitCommand.java:50)
    at grisu.gricli.Gricli.runCommand(Gricli.java:203)
    at grisu.gricli.Gricli.executionLoop(Gricli.java:86)
    at grisu.gricli.Gricli.main(Gricli.java:178)

Guess it interfers with the JSDL format :)

**Comment by makkus** [comment]
that is not supported in globus.

You can set the stdin though (although I'm not sure whether Gricli supports that). @yuriyh?

**Comment by sgenie68** [comment]
This is not a problem, but I think we are better off checking submit parameters before submitting and warning the user if there are invalid/unacceptable symbols.

**Comment by makkus** [comment]
Ok, makes sense.
