### ISSUE TITLE
findJobByDN exception

### ISSUE THREAD

**Issue by yuriyh** [grisu/grisu#62]
saw today on production backend - have no idea on user impact.

Caused by: org.hibernate.NonUniqueResultException: query did not return a unique result: 2
        at org.hibernate.impl.AbstractQueryImpl.uniqueElement(AbstractQueryImpl.java:868)
        at org.hibernate.impl.AbstractQueryImpl.uniqueResult(AbstractQueryImpl.java:859)
        at grisu.backend.hibernate.JobDAO.findJobByDN(JobDAO.java:124)
        at grisu.backend.model.User.getJobFromDatabaseOrFileSystem(User.java:1417)
        at grisu.control.serviceInterfaces.AbstractServiceInterface.getJsdlDocument(AbstractServiceInterface.java:2007)
        at sun.reflect.GeneratedMethodAccessor211.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)

**Comment by ndjones** [comment]
Any possibility this could be a symptom of the mismatched identity issue?
An unhandled exception (no matching DN) which then...

**Comment by yuriyh** [comment]
no, that error had very distinct signature (i will add alert to our rsyslog).

**Comment by mondkaefer** [comment]
I got this execption today, too, in a grisu backend set up on my desktop machine (develop branch)

**Comment by makkus** [comment]
This happens still every know and then. In order to get rid of it we'd proably need to investigate/review the hibernate setup we are using and what is causing the issue.

I eased the pain a bit by implementing a failsafe method to delete affected jobs though. So at least we don't have to manually edit the database to fix a user account.

**Comment by makkus** [comment]
This seems to have gone for good.
